// <auto-generated />
using Converter.Infostructure.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Converter.Infostructure.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20210817093150_migration_1")]
    partial class migration_1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("Converter.Core.Entities.CurrencyConverter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstCurrency")
                        .HasColumnType("TEXT");

                    b.Property<double>("FirstSum")
                        .HasColumnType("REAL");

                    b.Property<string>("SecondCurrency")
                        .HasColumnType("TEXT");

                    b.Property<double>("SecondSum")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("CurrencyConverters");
                });
#pragma warning restore 612, 618
        }
    }
}
